[experiment]
name = "FILL_ME_IN"
method = "calibrate"
seed = 42

[postgres]
path = "FILL_ME_IN"

[pool]
path = "FILL_ME_IN"

[data.test]
file = "test-tasks.json"
selection_seed = 42
expression = "FILL_ME_IN"

[measurement]
max_warmup_runs = 5
num_trials = 20
default_timeout_seconds = 300.0
