max_steps = 159
output_dir = "outputs/sft"
clean = true
dashboard = false

[run]
name = "protocol-sft-train-v1"

[model]
name = "empero-ai/Qwen3.8-4B-Distill"
impl = "custom"
attn = "flash_attention_2"
seq_len = 20480
optimization_dtype = "bfloat16"
reduce_dtype = "bfloat16"
compile = "None"

[model.lora]
rank = 16
alpha = 32
dropout = 0.0

[data]
name = "outputs/sft/protocol-sft-v1/prime"
splits = ["train"]
seq_len = 20480
batch_size = 1
micro_batch_size = 1
num_workers = 1
shuffle = true
seed = 20260830

[data.loss_mask]
system = false
user = false
assistant = true
tool = false

[val]
interval = 159
eval_on_start = true

[val.data]
name = "outputs/sft/protocol-sft-v1/prime"
splits = ["validation"]
seq_len = 20480
batch_size = 1
micro_batch_size = 1
num_workers = 1
shuffle = false
seed = 20260830

[val.data.loss_mask]
system = false
user = false
assistant = true
tool = false

[renderer]
name = "qwen3.5"
enable_thinking = false

[optim]
lr = 1e-4
weight_decay = 0.0

[ckpt]

[deployment]
gpus_per_node = 1
num_train_gpus = 1
